<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Login</name>
   <tag></tag>
   <elementGuidId>d6b62635-4774-444f-9841-e70e81c8201d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()=&quot;Sign In&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f47b799-81ea-47c2-9915-c6bd94d06dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_15kd2wesg _15kd2weu9   _15r4f4d154 _15r4f4d178 _15r4f4d1bi _15r4f4d1dr</value>
      <webElementGuid>9e216c32-1914-48bb-a57c-b42126be009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>641fb052-fff3-45c7-b002-ab26a945d2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Please enter email or phone number.Sign Inor sign in withGoogleFacebookDon’t have an account? Register here</value>
      <webElementGuid>df77cce3-b043-4092-b519-f59858597d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]</value>
      <webElementGuid>d79f7300-6e51-418a-94b4-014e3ce45a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='base'])[7]</value>
      <webElementGuid>4ee088c0-5f87-43ce-8fe7-103fe57dc5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div[2]</value>
      <webElementGuid>e7cc6663-b0e9-445e-a5cd-8a0c02011af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Shipping to All Over Indonesia'])[1]/following::div[3]</value>
      <webElementGuid>a39be064-14d1-4ff0-8795-d81ce355309e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow'])[1]/following::div[9]</value>
      <webElementGuid>3524d36b-2c67-4ff3-89f8-a597991c740a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>6164abc4-c1da-46e7-b3b3-1c3e3e2cedf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'base' and (text() = 'Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Please enter email or phone number.Sign Inor sign in withGoogleFacebookDon’t have an account? Register here' or . = 'Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Please enter email or phone number.Sign Inor sign in withGoogleFacebookDon’t have an account? Register here')]</value>
      <webElementGuid>9623d706-899b-437c-a9ef-5e1ad27fdc87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
