<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign InSign in to shop with vouchers, t_0800df</name>
   <tag></tag>
   <elementGuidId>66d6394a-0136-478e-b53b-df1daf924a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='base'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f84e9e42-aef9-4deb-af90-032c4a6a822f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_15kd2wesg _15kd2weu9   _15r4f4d154 _15r4f4d178 _15r4f4d1bi _15r4f4d1dr</value>
      <webElementGuid>d9428fa9-2738-4f7c-90a6-624878960989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>242def93-7679-4df8-a240-526921e0dd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Sign Inor sign in withGoogleFacebookDon’t have an account? Register here</value>
      <webElementGuid>9bfc64dd-48ca-4356-a43f-9f5fbdbeea64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]</value>
      <webElementGuid>395b1e06-83ea-4a46-92fe-c8b41796173e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='base'])[7]</value>
      <webElementGuid>674becd5-e1cd-4355-92f4-0811b48f385d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div[2]</value>
      <webElementGuid>ba2c5146-2826-470d-a090-d1e47e67bb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎉 BCA 68th Anniversary: Up to IDR 1 Mio OFF!'])[1]/following::div[3]</value>
      <webElementGuid>b1a5b2c1-315f-434a-8ada-5579a3cedf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow'])[1]/following::div[9]</value>
      <webElementGuid>a2fc5497-e3f3-4735-b0e9-2359b67a7d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>f3de7586-20d4-47b1-ad29-434b27464fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'base' and (text() = 'Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Sign Inor sign in withGoogleFacebookDon’t have an account? Register here' or . = 'Sign InSign in to shop with vouchers, track your order, and save your favorite products.Email or Phone Number*Sign Inor sign in withGoogleFacebookDon’t have an account? Register here')]</value>
      <webElementGuid>c9b30561-a1f3-48e8-bc51-52cf4c4df4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
