<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Would you like to sign out from your voil_b4c3a4</name>
   <tag></tag>
   <elementGuidId>452b2d2d-92d9-4b1c-93bd-a7307c3cbdeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='base'])[55]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._1jc0z8o0 > #base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2b2782a3-fa29-4890-818a-ceaa1209d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_15kd2weow   _15r4f4d9v _15r4f4dhd  _1ccbe2wa</value>
      <webElementGuid>ba775b33-c0af-4570-9a76-c406cc44d899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>ae332493-7308-4428-9f4e-94924f66fd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Would you like to sign out from your voilà.id account?</value>
      <webElementGuid>e8492755-2fdb-4fd2-a55d-623df7833035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r15:&quot;)/div[@id=&quot;base&quot;]/div[@class=&quot;_1jc0z8o0&quot;]/p[@id=&quot;base&quot;]</value>
      <webElementGuid>f6993ee5-35ee-48bd-bc84-cc7f85053b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@id='base'])[55]</value>
      <webElementGuid>7d828aac-a0cf-41d6-b9d1-8c6b18605873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='base']/div[2]/p)[12]</value>
      <webElementGuid>12d96fa1-6228-44e1-a7ad-57f8815b15bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More'])[1]/following::p[3]</value>
      <webElementGuid>742cfc06-f713-4768-80cf-f293088b2fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::p[1]</value>
      <webElementGuid>70aa85fc-461a-4d7c-9c1d-7591fdaa318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[3]/preceding::p[1]</value>
      <webElementGuid>f237f9bc-4a57-40e2-be4c-14538add8ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Would you like to sign out from your voilà.id account?']/parent::*</value>
      <webElementGuid>f1fa8ef6-5725-4c93-980d-29f36e6c6ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[2]/p</value>
      <webElementGuid>64c46dfb-c213-4228-bb34-500f9195dc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'base' and (text() = 'Would you like to sign out from your voilà.id account?' or . = 'Would you like to sign out from your voilà.id account?')]</value>
      <webElementGuid>6beba677-7de9-4c7b-92ef-a241dedb285b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
