<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Become a voil.id member andenjoy the be_8f7782 (1)</name>
   <tag></tag>
   <elementGuidId>109a440d-7ab7-4da3-914b-0ad3f33b5f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='base'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72683de5-a0d7-447a-8b15-7398ad63bf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_15kd2wesg _15kd2weu9   _15r4f4d154 _15r4f4d178 _15r4f4d1bi _15r4f4d1dr</value>
      <webElementGuid>5f12032f-0f0d-47b4-9c8a-f203eb1b229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>f5d464bf-c49a-4f15-a75b-a24c07c90ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Become a voilà.id member andenjoy the benefits100% AuthenticGet 100% authentic luxury items delivered to you.Welcome RewardsEnjoy 200.000 voilàPoints right after you register.Purchase HistoryTrack all of your online orders and in-boutique purchases.RegisterEmail or Phone Number*Please enter email or phone number.Password*Please create a password.I’d like to receive exclusive offers and the latest fashion updates from voilà.id.Register AccountBy creating an account, I agree to voilà.id’s Terms &amp; Conditions and Privacy Policy.or register withGoogleFacebookAlready registered? Sign In</value>
      <webElementGuid>6c27617f-3e81-4c92-8020-032b97885950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]</value>
      <webElementGuid>ea11149d-96f1-4efc-947c-e6914ea51cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='base'])[7]</value>
      <webElementGuid>604380f2-6635-4408-af4d-6c835685296f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div[2]</value>
      <webElementGuid>47c3e2f4-0636-49dc-9c21-7441c3b5862f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Shipping to All Over Indonesia'])[1]/following::div[3]</value>
      <webElementGuid>84322997-26be-4334-b2fd-ee18c62ca28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>fc9bb676-e549-4bcb-a229-3ed159c85d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'base' and (text() = 'Become a voilà.id member andenjoy the benefits100% AuthenticGet 100% authentic luxury items delivered to you.Welcome RewardsEnjoy 200.000 voilàPoints right after you register.Purchase HistoryTrack all of your online orders and in-boutique purchases.RegisterEmail or Phone Number*Please enter email or phone number.Password*Please create a password.I’d like to receive exclusive offers and the latest fashion updates from voilà.id.Register AccountBy creating an account, I agree to voilà.id’s Terms &amp; Conditions and Privacy Policy.or register withGoogleFacebookAlready registered? Sign In' or . = 'Become a voilà.id member andenjoy the benefits100% AuthenticGet 100% authentic luxury items delivered to you.Welcome RewardsEnjoy 200.000 voilàPoints right after you register.Purchase HistoryTrack all of your online orders and in-boutique purchases.RegisterEmail or Phone Number*Please enter email or phone number.Password*Please create a password.I’d like to receive exclusive offers and the latest fashion updates from voilà.id.Register AccountBy creating an account, I agree to voilà.id’s Terms &amp; Conditions and Privacy Policy.or register withGoogleFacebookAlready registered? Sign In')]</value>
      <webElementGuid>656f6d24-2c2c-4458-9718-144e699a094f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
