<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RegisterEmail or Phone NumberPlease ent_22d04c</name>
   <tag></tag>
   <elementGuidId>f2c5f1c1-f779-42a8-a094-e7f38b560a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='base'])[30]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form > #base > #base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54a69ba9-87a9-4148-9fb6-18344a95128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>j1jih78w j1jih79b  j1jih73h _15kd2weg     _15kd2weg</value>
      <webElementGuid>21446a48-be54-483a-b05d-bc04d94843de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>63fefaee-dead-4d78-8006-88e5e0962a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RegisterEmail or Phone Number*Please enter email or phone number.Password*</value>
      <webElementGuid>e9f9ee04-8d61-4db1-8654-eca12bb8503b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;vds-container ifvo3u0 wovzomn wovzo5a _15r4f4dvt _15r4f4dpf _15r4f4d96 _15r4f4dfk _15kd2weg&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/form[1]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]</value>
      <webElementGuid>a4655b15-f8c3-47cd-8c9f-dd5386af4fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='base'])[30]</value>
      <webElementGuid>8c649736-62e6-4938-90f5-93e852dd2b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='base']/div)[27]</value>
      <webElementGuid>ae80c394-c876-4a38-8814-22624d21faa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎉 BCA 68th Anniversary: Up to IDR 1 Mio OFF!'])[1]/following::div[27]</value>
      <webElementGuid>418a4bf1-be1c-40da-b753-cf2193730e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>da50bdd8-b66d-48fc-8740-41601b60da0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'base' and (text() = 'RegisterEmail or Phone Number*Please enter email or phone number.Password*' or . = 'RegisterEmail or Phone Number*Please enter email or phone number.Password*')]</value>
      <webElementGuid>a68a8c89-52c5-4d33-b3ed-270d0d7943c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
