<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chasing ON Love Exclusive IDR 150K Ju_a78a44 (1)</name>
   <tag></tag>
   <elementGuidId>a55507ab-1898-4e90-b3d3-f7cbb09fddc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='identifier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;identifier&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1193c69c-f5dc-41df-b9f4-a1cd2198395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75e7091a-9e88-4b0e-b4c2-62fb148c3b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ldkv8w1</value>
      <webElementGuid>680707bf-ec3e-4bbb-9c8a-0030b3eed275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>CT_component_identifier_input</value>
      <webElementGuid>470102b1-deb3-4019-ae59-3356f606c951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>9705c1e0-1555-47e9-82df-2f9fb14f60c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;vds-container ifvo3u0 wovzomn wovzo5a _15r4f4dvt _15r4f4dpf _15r4f4d96 _15r4f4dfk _15kd2weg&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/form[1]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;_1kg30950&quot;]/div[@class=&quot;_1kg30951 _1kg30952&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;yihd6a0 ldkv8w0&quot;]/input[@class=&quot;ldkv8w1&quot;]</value>
      <webElementGuid>beac5608-f40b-4909-b5c9-0455e9e2f8fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='identifier']</value>
      <webElementGuid>1a7393c6-f1be-4219-a4cc-26dbc3f812be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div/input</value>
      <webElementGuid>7a1df00f-b8bb-4822-b1fe-bc2da54674dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>516bd24f-c2b5-4c2b-9756-59dd495d934f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identifier']</value>
      <webElementGuid>8191f0d3-dd40-4607-9cb4-73b980b54a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
