<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chasing ON Love Exclusive IDR 150K Ju_a78a44 (4)</name>
   <tag></tag>
   <elementGuidId>e417a508-38d2-43e4-b37b-715ab3bbeb98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='identifier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;identifier&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1be8dda-68c8-48b8-8c5c-72d280004b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>699ee3aa-53e8-456a-8e73-1710c5e5de46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ldkv8w1</value>
      <webElementGuid>a7b00464-38a0-4740-b2e9-611f94dfb6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>CT_component_identifier_input</value>
      <webElementGuid>ebbf3a63-f4be-4de2-95bb-330cc862cc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>1dc2b78a-0425-4778-b646-79b69a18b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;voila-ui&quot;)/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;vds-container ifvo3u0 wovzomn wovzo5a _15r4f4dvt _15r4f4dpf _15r4f4d96 _15r4f4dfk _15kd2weg&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/form[1]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;_1kg30950&quot;]/div[@class=&quot;_1kg30951 _1kg30952&quot;]/div[@id=&quot;base&quot;]/div[@class=&quot;yihd6a0 ldkv8w0&quot;]/input[@class=&quot;ldkv8w1&quot;]</value>
      <webElementGuid>e88e3213-db6a-44e3-92af-d61ef7f2ced6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='identifier']</value>
      <webElementGuid>bf595c83-3bb9-487e-a693-c2ea4dbce043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div/input</value>
      <webElementGuid>4b339d3d-1984-4e42-9b55-053f30f7475d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88d2a498-c28a-4833-a818-b1e1f65a5b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identifier']</value>
      <webElementGuid>7f65af41-fa4f-44ad-8f1c-36df6a9ff24a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
